#!/usr/bin/env bash
set -euo pipefail

echo "SCAD toolchain"
echo "=============="
printf "OpenSCAD   : "
openscad --version 2>&1
printf "PythonSCAD : "
pythonscad --version 2>&1
printf "Python     : "
python3 --version
printf "Git        : "
git --version
